//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yayantary.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assortment
    {
        public int IDProduct { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Price { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
