//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yayantary.Properties
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TataryEntities1 : DbContext
    {
        private static TataryEntities1 _context;
        public TataryEntities1()
            : base("name=TataryEntities1")
        {
        }
        public static TataryEntities1 GetContext()
        {
            if (_context == null)
                _context = new TataryEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assortment> Assortment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
